### PR TITLE
Added Yogurl API

### PR DESCRIPTION
**Pull request by 45kb**
Hi, thanks for this great list!

I added Yogurl.io an open source API and CLI tool for instant file and code serving/sharing.

Let me know if you need some changes or anything wrong 👍

### CODE REVIEW

**Comment by 45kb** [comment]
@abhishekbanthia i think the page is rebuilding i can access it but try a little bit later :)

**Comment by abhishekbanthia** [comment]
Sure, I'll check this out after a couple of hours. Great work btw.

**Comment by 45kb** [comment]
@abhishekbanthia thanks a lot ok! however you can check even on some tools is up http://downforeveryoneorjustme.com/yogurl.io 👍

**Comment by abhishekbanthia** [comment]
Great; it's working for me now. Quick question: can you provide me with the link to the API documentation?

**Comment by 45kb** [comment]
@abhishekbanthia it's on the same page, look at the bottom "API" link :)

**Comment by abhishekbanthia** [comment]
I'm unable to access the API link. Here's what happening for me:

http://streamable.com/qmr12

**Comment by 45kb** [comment]
@abhishekbanthia ouch, sorry, i am going to fix this, it only works on Chrome, i'll ping you as it's all fixe, thanks!

**Comment by 45kb** [comment]
@abhishekbanthia should be everythings ok now, maybe try to delete your website cache 👍  👍

**Pull request merged**
