### PR TITLE
More public cryptocurrency apis

### PR DESCRIPTION
**Pull request by nimblefox**
This PR includes documentation changes listing more Public REST APIs

### CODE REVIEW

**Comment by abhishekbanthia** [comment]
Hi @nimblefox, nice additions. I'm unable to rebase because of conflicts. Can you take a look?

**Comment by nimblefox** [comment]
@abhishekbanthia - I did a rebase and added more apis

**Comment by abhishekbanthia** [comment]
Still seeing some conflicts!

screen shot 2018-09-04 at 11 56 06 am

**Comment by nimblefox** [comment]
@abhishekbanthia pull the latest and resolved those conflicts

**Comment by abhishekbanthia** [comment]
Still seeing conflicts.

**Pull request closed without merging**
