### PR TITLE
Added  Jekyll-theme-cayman

### PR DESCRIPTION
**Pull request by jsroyal**
@abhishekbanthia So need to do certain step follow for a webpage.
Click on the Settings tab.
Scroll down to the GitHub Pages section select source -> master.
Select a theme eg. cyman
Format according to see the content.
push the Commit.
After you take link to the web page and put into the header file.
Now look like -: 
image

### CODE REVIEW

**Comment by jsroyal** [comment]
@abhishekbanthia hey! Have you done?

**Comment by abhishekbanthia** [comment]
I really liked your initial idea but after checking your implementation, I'm afraid I can't move ahead.

**Comment by jsroyal** [comment]
What is the problem?
It can good design also.
Can you tell me what do you stuck?

**Comment by jsroyal** [comment]
If you still don't get it then can help to set up the GitHub web page.

**Comment by abhishekbanthia** [comment]
I've the following concerns:

1. For your implementation to work in sync with the repo, how would take care of all the new additions for the pull request that are approved?
2.  Your index links to the category don't work. 
3.  In the issue you've stated the website will improve social reach of the repo, how will this be achieved?
4. One of the features that I'll like to see is the ability to search for a category.

**Comment by jsroyal** [comment]
Okay.
> 1.For your implementation to work in sync with the repo, how would take care of all the new additions for the pull request that are approved?
So the web page we can implement in different branch gh-pages and time to time update and also it will not effect on the master.
>2.Your index links to the category don't work.
Actually, I did not the complete shape of theme according to what kind of you want.Table of contains can be implemented don't worry?
> 3. In the issue you've stated the website will improve the social reach of the repo, how will this be achieved?
Yeah! we can reach out through a link and it will open a responsive web page and also you want to buy a domain name for your blog then it can also be hosted here.
>4.One of the features that I'll like to see is the ability to search for a category.
It can be implemented by using tags or search bar on top of the web page so need to work on.
It will take time but it can be implemented very easily all this features.

**Comment by abhishekbanthia** [comment]
5. The address for the webpage should be something like public-apis.github.io
6. The website can be a Bootstrap single page with Jumbotron for header,and multiple table rows and columns consists of each API. Once user clicks, it will show a modal so the user can stick with the same page.

**Comment by jsroyal** [comment]
Whatever you like theme check it out here [Link](https://github.com/jekyll/jekyll/wiki/Themes)

**Pull request closed without merging**
