### PR TITLE
Renamed it to correct file name

### PR DESCRIPTION
**Pull request by GiacomoLaw**
So it appears to people creating pull requests and issues.

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
This means that the rules to contributing to the repo appears above, showing people what they should do.

**Comment by abhishekbanthia** [comment]
Hi @GiacomoLaw, welcome to the repo; I don't see how your commit will help with what you just mentioned. Closing for now, you can send me a new PR again.

**Comment by GiacomoLaw** [comment]
It will show as this:

w2lbzl

It means it is more noticeable, and people will be able to see it when they create a pr or an issue.

**Comment by abhishekbanthia** [comment]
Ahh, this is pretty useful. Thanks for the screenshot.

**Comment by GiacomoLaw** [comment]
No problem, sorry I didn't explain better earlier!

**Pull request merged**
