### PR TITLE
Satyr.io image placeholder

### PR DESCRIPTION
**Pull request by janpanschab**

### CODE REVIEW

**Comment by abhishekbanthia** [comment]
Hi @janpanschab, can you order your addition alphabetically? Thanks.

**Comment by janpanschab** [comment]
Hey @abhishekbanthia, I also order the whole section. Thanks

**Comment by abhishekbanthia** [comment]
Hi @janpanschab, I see there are some conflicts for your branch. Can you take a look?

**Comment by janpanschab** [comment]
@abhishekbanthia It looks like link to `https://developer.clarifai.com/guide/publicmodels#nsfw` is no longer available. Should I delete it?

**Comment by abhishekbanthia** [comment]
Ignore the Travis checks. Your readme file has conflicts with the master due to which I cannot rebase your changes.

**Comment by janpanschab** [comment]
Sorry, but It looks like this PR is mergeable. I see this above.
This branch has no conflicts with the base branch.

**Comment by abhishekbanthia** [comment]
screen shot 2017-03-06 at 10 32 21 am

**Comment by janpanschab** [comment]
@abhishekbanthia Please, could you try it once more? Thanks

**Comment by abhishekbanthia** [comment]
Ah. I can still see some conflicts. No worries, I'll add it manually. Thanks for the additions!

**Comment by janpanschab** [comment]
Thanks a lot!

**Comment by cockmeat** [comment]
Stop messaging me daam

**Pull request closed without merging**
