### PR TITLE
Added RandomUserGenerator API 

### PR DESCRIPTION
**Pull request by helios1101**
Added Random User Generator API for generation of random user information, much like Lorem Ipsum but here it's for the user.

### CODE REVIEW

**Comment by helios1101** [comment]
screenshot from 2018-11-27 13-49-06

Any help as to why this issue is popping, please.

**Comment by abhishekbanthia** [comment]
Can you order your addition alphabetically?

**Comment by helios1101** [comment]
All checks done and alphabetically sorted.

**Comment by abhishekbanthia** [comment]
Thank you!

**Pull request merged**
